version: '3'
services:
  nginx:
    # image: nginx:stable
    build: .
    volumes:
      #- ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/nginx.conf:/etc/opt/rh/rh-nginx116/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./gopl-zh:/opt/gopl-zh
    restart: always
    container_name: nginx
    ports:
     - 80:80
