version: '3'
services:
  nginx:
    # image: nginx:stable
    build: .
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
    restart: always
    ports:
     - 80:80
